version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasklist
    volumes:
      - /stuff/data/pgdata:/var/lib/postgresql/data
      #- ./restore:/restore
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:2021-04-19-1 #this is for arm image
    depends_on:
      - postgres
    ports:
      - "5556:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: onetwothree%
    restart: unless-stopped

volumes:
  postgres-data: 